//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento
    {
        public int Id { get; set; }
        public int IdPaciente { get; set; }
        public System.DateTime Data { get; set; }
        public string Anamnese { get; set; }
        public string ExameFisico { get; set; }
        public string CIDPrincipal { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataModificacao { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
